using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.ConstrainedExecution;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.Identity.Client.Extensions.Msal;
using Nop.Core.Caching;
using static Nop.Plugin.Crossroad.Integration.Services.Onix.Contracts;

namespace Nop.Plugin.Crossroad.Integration;

public class IntegrationDefaults
{
    public static CacheKey TokenExpirationCacheKey => new("CROSSROAD_INTEGRATION_TOKEN_EXPIRATION");

    public static CacheKey AccessTokenCacheKey => new("CROSSROAD_INTEGRATION_ACCESS_TOKEN");

    public const string Paperback = "B102";

    public const string Hardcover = "B409";

    public const string Epub = "E101";

    public const string Audio_MP3 = "A103";

    public const string Audio_CD = "A101";

    public const string ProductAttributeColumnName = "Type";

}

public abstract class OE_Enum
{
    private IDictionary<string, string> _enums = null;

    protected OE_Enum(IDictionary<string, string> enums)
    {
        _enums = enums;
    }

    public string GetValue(string key)
    {
        if (_enums.TryGetValue(key, out var value))
            return value;

        throw new System.ArgumentOutOfRangeException();
    }

    public List<string> GetKeys(string value)
    {
        return _enums.Where(x => x.Value == value).Select(x => x.Key).ToList();
    }

    public Dictionary<string, string> GetDictionary(List<string> keys)
    {
        return _enums.Where(x => keys.Contains(x.Key)).ToDictionary(x => x.Key, x => x.Value);
    }
}

public class OE_MeasureType_Enum : OE_Enum
{
    public OE_MeasureType_Enum() : base(new Dictionary<string, string>
    {
        {"", "undefined"},
        {"01", "Height"},
        {"02", "Width"},
        {"03", "Thickness"},
        {"04", "Page trim height"},
        {"05", "Page trim width"},
        {"08", "Unit weight"},
        {"09", "Diameter (sphere)"},
        {"10", "Unfolded/unrolled sheet height"},
        {"11", "Unfolded/unrolled sheet width"},
        {"12", "Diameter (tube or cylinder)"},
        {"13", "Rolled sheet package side measure"},
        {"14", "Unpackaged height"},
        {"15", "Unpackaged width"},
        {"16", "Unpackaged thickness"},
        {"17", "Total battery weight"},
        {"18", "Total weight of Lithium"},
        {"06", "Unit volume"},
        {"07", "Unit capacity"},
        {"19", "Assembled length"},
        {"20", "Assembled width"},
        {"21", "Assembled height"},
        {"23", "Carton length"},
        {"24", "Carton width"},
        {"25", "Carton height"},
        {"26", "Carton weight"},
        {"27", "Pallet length"},
        {"28", "Pallet width"},
        {"29", "Pallet height"},
        {"30", "Pallet weight"},
        {"22", "Unpackaged unit weight"},
    })
    {
    }
}

public class OE_ExtentUnit_Enum : OE_Enum
{
    public OE_ExtentUnit_Enum() : base(new Dictionary<string, string>
    {
     { "", "undefined"},
     {"00", "Physical pieces"},
     {"01", "Characters"},
     {"02", "Words"},
     {"03", "Pages"},
     {"04", "Hours (integer and decimals)"},
     {"05", "Minutes (integer and decimals)"},
     {"06", "Seconds (integer only)"},
     {"11", "Tracks"},
     {"12", "Discs"},
     {"14", "Hours HHH"},
     {"15", "Hours and minutes HHHMM"},
     {"16", "Hours minutes seconds HHHMMSS"},
     {"17", "Bytes"},
     {"18", "Kbytes"},
     {"19", "Mbytes"},
     {"31", "Chapters"},
    })
    {
    }
}

public class OE_ExtentType_Enum : OE_Enum
{
    public OE_ExtentType_Enum() : base(new Dictionary<string, string>
    {
        {"", "undefined"},
        {"00", "Main content page count"},
        {"02", "Total text length"},
        {"03", "Front matter page count"},
        {"04", "Back matter page count"},
        {"05", "Total numbered pages"},
        {"06", "Production page count"},
        {"07", "Absolute page count"},
        {"08", "Number of pages in print counterpart"},
        {"09", "Duration"},
        {"10", "Notional number of pages in digital product"},
        {"11", "Content page count"},
        {"12", "Total unnumbered insert page count"},
        {"13", "Duration of introductory matter"},
        {"14", "Duration of main content"},
        {"15", "Duration of back matter"},
        {"16", "Production duration"},
        {"22", "Filesize"},
        {"23", "Storage filesize"},
        {"17", "Number of cards"},
        {"18", "Number of write-in pages"},
    })
    {

    }
}

public class OE_ContributorRole_Enum : OE_Enum
{
    public OE_ContributorRole_Enum() : base(new Dictionary<string, string>
    {
        {"", "undefined"},
        {"A01", "By (author)"},
        {"A02", "With"},
        {"A03", "Screenplay by"},
        {"A04", "Libretto by"},
        {"A05", "Lyrics by"},
        {"A06", "By (composer)"},
        {"A07", "By (artist)"},
        {"A08", "By (photographer)"},
        {"A09", "Created by"},
        {"A10", "From an idea by"},
        {"A11", "Designed by"},
        {"A12", "Illustrated by"},
        {"A13", "Photographs by"},
        {"A14", "Text by"},
        {"A15", "Preface by"},
        {"A16", "Prologue by"},
        {"A17", "Summary by"},
        {"A18", "Supplement by"},
        {"A19", "Afterword by"},
        {"A20", "Notes by"},
        {"A21", "Commentaries by"},
        {"A22", "Epilogue by"},
        {"A23", "Foreword by"},
        {"A24", "Introduction by"},
        {"A25", "Footnotes by"},
        {"A26", "Memoir by"},
        {"A27", "Experiments by"},
        {"A28", "Interpreted through"},
        {"A29", "Introduction and notes by"},
        {"A30", "Software written by"},
        {"A31", "Book and lyrics by"},
        {"A32", "Contributions by"},
        {"A33", "Appendix by"},
        {"A34", "Index by"},
        {"A35", "Drawings by"},
        {"A36", "Cover design or artwork by"},
        {"A37", "Preliminary work by"},
        {"A38", "Original author"},
        {"A39", "Maps by"},
        {"A40", "Inked or colored by"},
        {"A41", "Paper engineering by"},
        {"A42", "Continued by"},
        {"A43", "Interviewer"},
        {"A44", "Interviewee"},
        {"A45", "Comic script by"},
        {"A46", "Inker"},
        {"A47", "Colorist"},
        {"A48", "Letterer"},
        {"A49", "Cover inker"},
        {"A50", "Cover colorist"},
        {"A51", "Research by"},
        {"A52", "Original character design"},
        {"A99", "Other primary creator"},
        {"B01", "Edited by"},
        {"B02", "Revised by"},
        {"B03", "Retold by"},
        {"B04", "Abridged by"},
        {"B05", "Adapted by"},
        {"B06", "Translated by"},
        {"B07", "As told by"},
        {"B08", "Translated with commentary by"},
        {"B09", "Series edited by"},
        {"B10", "Edited and translated by"},
        {"B11", "Editor-in-chief"},
        {"B12", "Guest editor"},
        {"B13", "Volume editor"},
        {"B14", "Editorial board member"},
        {"B15", "Editorial coordination by"},
        {"B16", "Managing editor"},
        {"B17", "Founded by"},
        {"B18", "Prepared for publication by"},
        {"B19", "Associate editor"},
        {"B20", "Consultant editor"},
        {"B21", "General editor"},
        {"B22", "Dramatized by"},
        {"B23", "General rapporteur"},
        {"B24", "Literary editor"},
        {"B25", "Arranged by (music)"},
        {"B26", "Technical editor"},
        {"B27", "Thesis advisor or supervisor"},
        {"B28", "Thesis examiner"},
        {"B29", "Scientific editor"},
        {"B30", "Historical advisor"},
        {"B31", "Original editor"},
        {"B32", "Translation revised by"},
        {"B33", "Transcribed by"},
        {"B34", "Sensitivity reader / editor"},
        {"B99", "Other adaptation by"},
        {"C01", "Compiled by"},
        {"C02", "Selected by"},
        {"C03", "Non-text material selected by"},
        {"C04", "Curated by"},
        {"C99", "Other compilation by"},
        {"D01", "Producer"},
        {"D02", "Director"},
        {"D03", "Conductor"},
        {"D04", "Choreographer"},
        {"D99", "Other direction by"},
        {"E01", "Actor"},
        {"E02", "Dancer"},
        {"E03", "Narrator"},
        {"E04", "Commentator"},
        {"E05", "Vocal soloist"},
        {"E06", "Instrumental soloist"},
        {"E07", "Read by"},
        {"E08", "Performed by (orchestra, band, ensemble)"},
        {"E09", "Speaker"},
        {"E10", "Presenter"},
        {"E11", "Introduction read by"},
        {"E99", "Performed by"},
        {"F01", "Filmed/photographed by"},
        {"F02", "Editor (film or video)"},
        {"F99", "Other recording by"},
        {"Z01", "Assisted by"},
        {"Z02", "Honored/dedicated to"},
        {"Z06", "In association with"},
        {"Z98", "(Various roles)"},
        {"Z99", "Other"},
        {"Z03", "Enacting jurisdiction"},
        {"Z04", "Peer reviewed"},
        {"Z05", "Posthumously completed by"},
    })
    {
    }

}

public class OE_PublishingStatus_Enum : OE_Enum
{
    public OE_PublishingStatus_Enum() : base(new Dictionary<string, string>
    {
        {"", "undefined"},
        {"00", "Unspecified"},
        {"01", "Cancelled"},
        {"02", "Forthcoming"},
        {"03", "Postponed indefinitely"},
        {"04", "Active"},
        {"05", "No longer our product"},
        {"06", "Out of stock indefinitely"},
        {"07", "Out of print"},
        {"08", "Inactive"},
        {"09", "Unknown"},
        {"10", "Remaindered"},
        {"11", "Withdrawn from sale"},
        {"12", "Recalled"},
        {"13", "Active, but not sold separately"},
        {"15", "Recalled"},
        {"16", "Temporarily withdrawn from sale"},
        {"17", "Permanently withdrawn from sale"},
        {"18", "Active, but not sold as set"},
    })
    {
    }
}

public class OE_TextType_Enum : OE_Enum
{
    public OE_TextType_Enum() : base(new Dictionary<string, string>
    {
        {"", "undefined"},
        {"01", "Sender-defined text"},
        {"02", "Short description/annotation"},
        {"03", "Description"},
        {"04", "Table of contents"},
        {"05", "Primary cover copy"},
        {"06", "Review quote"},
        {"07", "Review quote: previous edition"},
        {"08", "Review quote: previous work"},
        {"09", "Endorsement"},
        {"10", "Promotional headline"},
        {"11", "Feature"},
        {"12", "Biographical note"},
        {"13", "Publisher’s notice"},
        {"14", "Excerpt"},
        {"15", "Index"},
        {"16", "Short description/annotation for collection"},
        {"17", "Description for collection"},
        {"18", "New feature"},
        {"19", "Version history"},
        {"20", "Open access statement"},
        {"21", "Digital exclusivity statement"},
        {"22", "Official recommendation"},
        {"23", "JBPA description"},
        {"24", "schema.org snippet"},
        {"25", "Errata"},
        {"26", "Introduction"},
        {"27", "Secondary cover copy"},
        {"28", "Full cast and credit list"},
        {"29", "Bibliography"},
        {"30", "Abstract"},
        {"31", "Rules or instructions"},
        {"32", "List of contents"},
        {"33", "Short description/annotation for imprint"},
        {"34", "Description for imprint"},
        {"35", "Short description/annotation for publisher"},
        {"36", "Description for publisher"},
        {"37", "Cover line"},
    })
    {
    }
}

public class OE_SubjectSchemeIdentifier_Enum : OE_Enum
{
    public OE_SubjectSchemeIdentifier_Enum() : base(new Dictionary<string, string>
    {
       {"", "undefined"},
        {"01", "Dewey"},
        {"02", "Abridged Dewey"},
        {"03", "LC classification"},
        {"04", "LC subject heading"},
        {"05", "NLM classification"},
        {"06", "MeSH heading"},
        {"07", "NAL subject heading"},
        {"08", "AAT"},
        {"09", "UDC"},
        {"10", "BISAC Subject Heading"},
        {"11", "BISAC Regional theme"},
        {"12", "BIC subject category"},
        {"13", "BIC geographical qualifier"},
        {"14", "BIC language qualifier (language as subject)"},
        {"15", "BIC time period qualifier"},
        {"16", "BIC educational purpose qualifier"},
        {"17", "BIC reading level and special interest qualifier"},
        {"18", "DDC-Sachgruppen der Deutschen Nationalbibliografie"},
        {"19", "LC fiction genre heading"},
        {"20", "Keywords"},
        {"21", "BIC children’s book marketing category"},
        {"22", "BISAC Merchandising Theme"},
        {"23", "Publisher’s own category code"},
        {"24", "Proprietary subject scheme"},
        {"25", "Tabla de materias ISBN"},
        {"26", "Warengruppen-Systematik des deutschen Buchhandels"},
        {"27", "SWD (Schlagwortnormdatei – Subject Headings Authority File in the German-speaking countries. See http://www.dnb.de/standardisierung/normdateien/swd.htm (in German) and http://www.dnb.de/eng/standardisierung/normdateien/swd.htm (English). DEPRECATED in favor of the GND)"},
        {"28", "Thèmes Electre"},
        {"29", "CLIL Classification thématique"},
        {"30", "DNB-Sachgruppen"},
        {"31", "NUGI"},
        {"32", "NUR"},
        {"33", "ECPA Christian Book Category"},
        {"34", "SISO"},
        {"35", "Korean Decimal Classification (KDC)"},
        {"36", "DDC Deutsch 22"},
        {"37", "Bokgrupper"},
        {"38", "Varegrupper"},
        {"39", "Læreplaner-KL06"},
        {"40", "Nippon Decimal Classification"},
        {"41", "BSQ"},
        {"42", "ANELE Materias"},
        {"43", "Utdanningsprogram"},
        {"44", "Programområde"},
        {"45", "Undervisningsmateriell"},
        {"46", "Norsk DDK"},
        {"47", "Varugrupper"},
        {"48", "SAB"},
        {"49", "Läromedelstyp"},
        {"50", "Förhandsbeskrivning"},
        {"51", "Spanish ISBN UDC subset"},
        {"52", "ECI subject categories"},
        {"53", "Soggetto CCE"},
        {"54", "Qualificatore geografico CCE"},
        {"55", "Qualificatore di lingua CCE"},
        {"56", "Qualificatore di periodo storico CCE"},
        {"57", "Qualificatore di livello scolastico CCE"},
        {"58", "Qualificatore di età di lettura CCE"},
        {"59", "VdS Bildungsmedien Fächer"},
        {"60", "Fagkoder"},
        {"61", "JEL classification"},
        {"62", "CSH"},
        {"63", "RVM"},
        {"64", "YSA"},
        {"65", "Allärs"},
        {"66", "YKL"},
        {"67", "MUSA"},
        {"68", "CILLA"},
        {"69", "Kaunokki"},
        {"70", "Bella"},
        {"71", "YSO"},
        {"72", "PTO"},
        {"73", "Suomalainen kirja-alan luokitus"},
        {"74", "Sears"},
        {"75", "BIC E4L"},
        {"76", "CSR"},
        {"77", "Suomalainen oppiaineluokitus"},
        {"78", "Japanese book trade C-Code"},
        {"79", "Japanese book trade Genre Code"},
        {"80", "Fiktiivisen aineiston lisäluokitus"},
        {"81", "Arabic Subject heading scheme"},
        {"82", "Arabized BIC subject category"},
        {"83", "Arabized LC subject headings"},
        {"84", "Bibliotheca Alexandrina Subject Headings"},
        {"85", "Postal code"},
        {"86", "GeoNames ID"},
        {"87", "NewBooks Subject Classification"},
        {"88", "Chinese Library Classification"},
        {"89", "NTCPDSAC Classification"},
        {"90", "Season and Event Indicator"},
        {"91", "GND"},
        {"92", "BIC UKSLC"},
        {"93", "Thema subject category"},
        {"94", "Thema place qualifier"},
        {"95", "Thema language qualifier"},
        {"96", "Thema time period qualifier"},
        {"97", "Thema educational purpose qualifier"},
        {"98", "Thema interest age / special interest qualifier"},
        {"99", "Thema style qualifier"},
        {"A2", "Ämnesord"},
        {"A3", "Statystyka Książek Papierowych, Mówionych I Elektronicznych"},
        {"A4", "CCSS"},
        {"A5", "Rameau"},
        {"A6", "Nomenclature discipline scolaire"},
        {"A7", "ISIC"},
        {"A8", "LC Children’s Subject Headings"},
        {"A9", "Ny Läromedel"},
        {"B0", "EuroVoc"},
        {"B1", "BISG Educational Taxonomy"},
        {"B2", "Keywords (not for display)"},
        {"B3", "Nomenclature Diplôme"},
        {"B4", "Key character names"},
        {"B5", "Key place names"},
        {"B6", "FAST"},
        {"B7", "NGSS"},
        {"B8", "MVB-Lesemotive"},
        {"B9", "LOPS21 Subject module"},
        {"C0", "Læreplaner-LK20"},
        {"C1", "Kompetansemål-LK20"},
        {"C2", "Kompetansemålsett-LK20"},
        {"C3", "Tverrfaglige temaer-LK20"},
        {"C4", "CLIL – Type d’article scolaire"},
        {"C5", "GAR – Type pédagogique"},
        {"C6", "ISCED-F"},
        {"C7", "Klassifikationen von Spielen, Puzzles und Spielwaren"},
        {"C8", "NBVok NTSF"},
        {"C9", "JPRO Genre"},
        {"D0", "KAUNO"},
        {"D1", "SLM"},
        {"D2", "YSO-places"},
    })
    {
    }
}

public class OE_AncillaryContentType_Enum : OE_Enum
{
    public OE_AncillaryContentType_Enum() : base(new Dictionary<string, string>
    {
        {"", "undefined"},
        {"00", "Unspecified, see description"},
        {"01", "Illustrations, black and white"},
        {"02", "Illustrations, color"},
        {"03", "Halftones, black and white"},
        {"04", "Halftones, color"},
        {"05", "Line drawings, black and white"},
        {"06", "Line drawings, color"},
        {"07", "Tables, black and white"},
        {"08", "Tables, color"},
        {"09", "Illustrations, unspecified"},
        {"10", "Halftones, unspecified"},
        {"11", "Tables, unspecified"},
        {"12", "Line drawings, unspecified"},
        {"13", "Halftones, duotone"},
        {"14", "Maps"},
        {"15", "Frontispiece"},
        {"16", "Diagrams"},
        {"17", "Figures"},
        {"18", "Charts"},
        {"19", "Recorded music items"},
        {"20", "Printed music items"},
        {"21", "Graphs"},
        {"22", "Plates, unspecified"},
        {"23", "Plates, black and white"},
        {"24", "Plates, color"},
        {"25", "Index"},
        {"26", "Bibliography"},
        {"27", "Inset maps"},
        {"28", "GPS grids"},
        {"29", "Glossary"},
        {"30", "Table of contents"},
        {"31", "Gazetteer"},
    })
    {
    }
}

public class OE_ProductFormDetail_Enum : OE_Enum
{
    public OE_ProductFormDetail_Enum() : base(new Dictionary<string, string>
    {
     {"", "undefined"},
 {"A101", "CD standard audio format"},
 {"A102", "SACD super audio format"},
 {"A103", "MP3 format"},
 {"A104", "WAV format"},
 {"A105", "Real Audio format"},
 {"A106", "WMA"},
 {"A107", "AAC"},
 {"A108", "Ogg/Vorbis"},
 {"A109", "Audible"},
 {"A110", "FLAC"},
 {"A111", "AIFF"},
 {"A112", "ALAC"},
 {"A201", "DAISY 2: full audio with title only (no navigation)"},
 {"A202", "DAISY 2: full audio with navigation (no text)"},
 {"A203", "DAISY 2: full audio with navigation and partial text"},
 {"A204", "DAISY 2: full audio with navigation and full text"},
 {"A205", "DAISY 2: full text with navigation and partial audio"},
 {"A206", "DAISY 2: full text with navigation and no audio"},
 {"A207", "DAISY 3: full audio with title only (no navigation)"},
 {"A208", "DAISY 3: full audio with navigation (no text)"},
 {"A209", "DAISY 3: full audio with navigation and partial text"},
 {"A210", "DAISY 3: full audio with navigation and full text"},
 {"A211", "DAISY 3: full text with navigation and partial audio"},
 {"A212", "DAISY 3: full text with navigation and no audio"},
 {"A301", "Standalone audio"},
 {"A302", "Readalong audio"},
 {"A303", "Playalong audio"},
 {"A304", "Speakalong audio"},
 {"A305", "Synchronised audio"},
 {"A410", "Mono"},
 {"A420", "Stereo"},
 {"A421", "Stereo 2.1"},
 {"A441", "Surround 4.1"},
 {"A451", "Surround 5.1"},
 {"B101", "Mass market (rack) paperback"},
 {"B102", "Trade paperback (US)"},
 {"B103", "Digest format paperback"},
 {"B104", "A-format paperback"},
 {"B105", "B-format paperback"},
 {"B106", "Trade paperback (UK)"},
 {"B107", "Tall rack paperback (US)"},
 {"B108", "A5 size Tankobon"},
 {"B109", "JIS B5 size Tankobon"},
 {"B110", "JIS B6 size Tankobon"},
 {"B111", "A6 size Bunko"},
 {"B112", "B40-dori Shinsho"},
 {"B113", "Pocket (Sweden, Norway, France)"},
 {"B114", "Storpocket (Sweden)"},
 {"B115", "Kartonnage (Sweden)"},
 {"B116", "Flexband (Sweden)"},
 {"B117", "Mook / Bookazine"},
 {"B118", "Dwarsligger"},
 {"B119", "46 size"},
 {"B120", "46-Henkei size"},
 {"B121", "A4"},
 {"B122", "A4-Henkei size"},
 {"B123", "A5-Henkei size"},
 {"B124", "B5-Henkei size"},
 {"B125", "B6-Henkei size"},
 {"B126", "AB size"},
 {"B127", "JIS B7 size"},
 {"B128", "Kiku size"},
 {"B129", "Kiku-Henkei size"},
 {"B130", "JIS B4 size"},
 {"B131", "Paperback (DE)"},
 {"B132", "Libro de bolsillo"},
 {"B133", "Pocket-sized"},
 {"B134", "A5"},
 {"B141", "B4-Henkei"},
 {"B201", "Coloring / join-the-dot book"},
 {"B202", "Lift-the-flap book"},
 {"B204", "Miniature book"},
 {"B205", "Moving picture / flicker book"},
 {"B206", "Pop-up book"},
 {"B207", "Scented / ‘smelly’ book"},
 {"B208", "Sound story / ‘noisy’ book"},
 {"B209", "Sticker book"},
 {"B210", "Touch-and-feel book"},
 {"B212", "Die-cut book"},
 {"B213", "Book-as-toy"},
 {"B214", "Soft-to-touch book"},
 {"B215", "Fuzzy-felt book"},
 {"B216", "Press-out puzzle pieces"},
 {"B221", "Picture book"},
 {"B222", "‘Carousel’ book"},
 {"B223", "Pull-the-tab book"},
 {"B225", "Cut-out pieces"},
 {"B301", "Loose leaf or partwork – sheets / parts and binder / wallet"},
 {"B302", "Loose leaf or partwork – binder / wallet only"},
 {"B303", "Loose leaf or partwork – sheets / parts only"},
 {"B304", "Sewn"},
 {"B305", "Unsewn / adhesive bound"},
 {"B306", "Library binding"},
 {"B307", "Reinforced binding"},
 {"B308", "Half bound"},
 {"B309", "Quarter bound"},
 {"B310", "Saddle-sewn"},
 {"B311", "Comb bound"},
 {"B312", "Wire-O"},
 {"B313", "Concealed wire"},
 {"B314", "Coiled wire bound"},
 {"B315", "Trade binding"},
 {"B316", "Swiss binding"},
 {"B317", "Notched binding"},
 {"B400", "Self-covered"},
 {"B401", "Cloth over boards"},
 {"B402", "Paper over boards"},
 {"B403", "Leather, real"},
 {"B404", "Leather, imitation"},
 {"B405", "Leather, bonded"},
 {"B406", "Vellum"},
 {"B409", "Cloth"},
 {"B410", "Imitation cloth"},
 {"B411", "Velvet"},
 {"B412", "Flexible plastic/vinyl cover"},
 {"B413", "Plastic-covered"},
 {"B414", "Vinyl-covered"},
 {"B415", "Laminated cover"},
 {"B416", "Card cover"},
 {"B417", "Duplex-printed cover"},
 {"B418", "Paper cover"},
 {"B501", "With dust jacket"},
 {"B502", "With printed dust jacket"},
 {"B503", "With translucent dust cover"},
 {"B504", "With flaps"},
 {"B505", "With thumb index"},
 {"B506", "With ribbon marker(s)"},
 {"B507", "With zip fastener"},
 {"B508", "With button snap fastener"},
 {"B509", "With leather edge lining"},
 {"B510", "Rough front"},
 {"B511", "Foldout"},
 {"B512", "Wide margin"},
 {"B513", "With fastening strap"},
 {"B514", "With perforated pages"},
 {"B515", "Acid-free paper"},
 {"B516", "Archival paper"},
 {"B517", "With elasticated strap"},
 {"B522", "Mineral paper"},
 {"B523", "With accessibility claim ticket"},
 {"B601", "Turn-around book"},
 {"B602", "Unflipped manga format"},
 {"B603", "Back-to-back book"},
 {"B604", "Flipped manga format"},
 {"B610", "Syllabification"},
 {"B701", "UK Uncontracted Braille"},
 {"B702", "UK Contracted Braille"},
 {"B703", "US Braille"},
 {"B704", "US Uncontracted Braille"},
 {"B705", "US Contracted Braille"},
 {"B706", "Unified English Braille"},
 {"B707", "Moon"},
 {"B708", "Unified English Uncontracted Braille"},
 {"B709", "Unified English Contracted Braille"},
 {"D101", "Real Video format"},
 {"D102", "Quicktime format"},
 {"D103", "AVI format"},
 {"D104", "Windows Media Video format"},
 {"D105", "MPEG-4"},
 {"D201", "MS-DOS"},
 {"D202", "Windows"},
 {"D203", "Macintosh"},
 {"D204", "UNIX / LINUX"},
 {"D205", "Other operating system(s)"},
 {"D206", "Palm OS"},
 {"D207", "Windows Mobile"},
 {"D301", "Microsoft XBox"},
 {"D302", "Nintendo Gameboy Color"},
 {"D303", "Nintendo Gameboy Advanced"},
 {"D304", "Nintendo Gameboy"},
 {"D305", "Nintendo Gamecube"},
 {"D306", "Nintendo 64"},
 {"D307", "Sega Dreamcast"},
 {"D308", "Sega Genesis/Megadrive"},
 {"D309", "Sega Saturn"},
 {"D310", "Sony PlayStation 1"},
 {"D311", "Sony PlayStation 2"},
 {"D312", "Nintendo Dual Screen"},
 {"D313", "Sony PlayStation 3"},
 {"D314", "Microsoft Xbox 360"},
 {"D315", "Nintendo Wii"},
 {"D316", "Sony PlayStation Portable (PSP)"},
 {"E100", "Other"},
 {"E101", "EPUB"},
 {"E102", "OEB"},
 {"E103", "DOC"},
 {"E104", "DOCX"},
 {"E105", "HTML"},
 {"E106", "ODF"},
 {"E107", "PDF"},
 {"E108", "PDF/A"},
 {"E109", "RTF"},
 {"E110", "SGML"},
 {"E111", "TCR"},
 {"E112", "TXT"},
 {"E113", "XHTML"},
 {"E114", "zTXT"},
 {"E115", "XPS"},
 {"E116", "Amazon Kindle"},
 {"E117", "BBeB"},
 {"E118", "DXReader"},
 {"E119", "EBL"},
 {"E120", "Ebrary"},
 {"E121", "eReader"},
 {"E122", "Exebook"},
 {"E123", "Franklin eBookman"},
 {"E124", "Gemstar Rocketbook"},
 {"E125", "iSilo"},
 {"E126", "Microsoft Reader"},
 {"E127", "Mobipocket"},
 {"E128", "MyiLibrary"},
 {"E129", "NetLibrary"},
 {"E130", "Plucker"},
 {"E131", "VitalBook"},
 {"E132", "Vook"},
 {"E133", "Google Edition"},
 {"E134", "Book ‘app’ for iOS"},
 {"E135", "Book ‘app’ for Android"},
 {"E136", "Book ‘app’ for other operating system"},
 {"E139", "CEB"},
 {"E140", "CEBX"},
 {"E141", "iBook"},
 {"E142", "ePIB"},
 {"E143", "SCORM"},
 {"E144", "EBP"},
 {"E145", "Page Perfect"},
 {"E146", "BRF"},
 {"E147", "Erudit"},
 {"E150", "EPUB/A"},
 {"E200", "Reflowable"},
 {"E201", "Fixed format"},
 {"E202", "Readable offline"},
 {"E203", "Requires network connection"},
 {"E204", "Content removed"},
 {"E210", "Landscape"},
 {"E211", "Portrait"},
 {"E221", "5:4"},
 {"E222", "4:3"},
 {"E223", "3:2"},
 {"E224", "16:10"},
 {"E225", "16:9"},
 {"L101", "Laminated"},
 {"P101", "Desk calendar or diary"},
 {"P102", "Mini calendar or pocket diary"},
 {"P103", "Engagement calendar or Appointment diary"},
 {"P104", "Day by day calendar"},
 {"P105", "Poster calendar"},
 {"P106", "Wall calendar"},
 {"P107", "Perpetual calendar or diary"},
 {"P108", "Advent calendar"},
 {"P109", "Bookmark calendar"},
 {"P110", "Student or Academic calendar or diary"},
 {"P111", "Project calendar"},
 {"P112", "Almanac calendar"},
 {"P113", "Other calendar, diary or organiser"},
 {"P114", "Other calendar or organiser product"},
 {"P120", "Picture story cards"},
 {"P201", "Hardback (stationery)"},
 {"P202", "Paperback / softback (stationery)"},
 {"P203", "Spiral bound (stationery)"},
 {"P204", "Leather / fine binding (stationery)"},
 {"P301", "With hanging strips"},
 {"V201", "PAL"},
 {"V202", "NTSC"},
 {"V203", "SECAM"},
 {"V205", "HD"},
 {"V206", "UHD"},
 {"V207", "3D video"},
 {"V210", "Closed captions"},
 {"V211", "Open captions"},
 {"V212", "Transcript"},
 {"V213", "Sign language interpretation"},
 {"V220", "Home use"},
 {"V221", "Classroom use"},
 {"B518", "With serialized authenticity token"},
 {"B519", "With dust jacket poster"},
 {"A310", "Sound effects"},
 {"A311", "Background music"},
 {"D317", "Sony PlayStation 3 (Use with Product Form code DB, DI, DO or E* as applicable. DEPRECATED)"},
 {"D318", "Sony PlayStation 4"},
 {"D319", "Sony PlayStation Vita"},
 {"D320", "Microsoft Xbox One"},
 {"D321", "Nintendo Switch"},
 {"D322", "Nintendo Wii U"},
 {"E148", "Amazon Kindle Print Replica"},
 {"P115", "Family planner"},
 {"A113", "W3C Audiobook format"},
 {"B135", "Mass market max paperback"},
 {"D323", "Sony PlayStation 5"},
 {"D324", "Microsoft Xbox Series X / S"},
 {"E149", "Comic Book Archive"},
 {"P116", "Postcard calendar"},
 {"P121", "Flash cards"},
 {"P122", "Reference cards"},
 {"P123", "Recreation cards"},
 {"P124", "Postcards"},
 {"P125", "Greeting cards"},
 {"P126", "Gift cards"},
 {"Z101", "Wooden"},
 {"Z102", "Plastic"},
 {"Z103", "Board"},
 {"Z111", "3D puzzle"},
 {"Z112", "Noisy kit / puzzle / toy"},
 {"Z113", "Puppet"},
 {"Z121", "Extra large pieces"},
 {"A400", "64kbits/s"},
 {"A401", "128kbits/s"},
 {"A402", "192kbits/s"},
 {"A403", "256kbits/s"},
 {"A404", "320kbits/s"},
 {"B420", "Delicate cover / jacket finish"},
 {"B520", "Rounded corners"},
 {"E212", "Square"},
 {"E226", "18:9"},
 {"E227", "21:9"},
 {"B318", "Lay-flat binding"},
 {"P305", "Single-sided"},
 {"P306", "Double-sided"},
 {"P127", "Certificate cards"},
 {"B521", "Splashproof"},
 {"B750", "Tactile images"},
 {"B751", "Lenticular images"},
 {"B752", "Anaglyph images"},
 {"C750", "Raised 3D relief"},
 {"A312", "Without background sounds"},
 {"A471", "Dolby Atmos"},
 {"B224", "‘Wordless’ book"},
 {"B605", "Variant turn-around book"},
 {"B606", "Page progression LTR"},
 {"B607", "Page progression RTL"},
 {"B608", "Page progression TTB"},
 {"B609", "Page progression other"},
 {"B611", "Upper case only"},
 {"E205", "Visible page numbering"},
 {"E206", "No preferred page progression"},
 {"E213", "Vertical scrolling"},
 {"P091", "Calendar with writein space"},
 {"P092", "Calendar without write-in space"},
 {"P096", "Multiple months per page"},
 {"P097", "One month per page"},
 {"P098", "One week per page"},
 {"P099", "One day per page"},
 {"P131", "Blank calendar"},
 {"P132", "Panoramic calendar"},
 {"P133", "Columnar calendar"},
 {"B139", "Comic book size (US)"},
 {"B140", "Comic album size (Euro)"},
 {"B407", "Head and tail bands"},
 {"B408", "Decorated endpapers"},
 {"P134", "Square calendar"},
    })
    {
    }
}

public class OE_ProductIdentifierType_Enum : OE_Enum
{
    public OE_ProductIdentifierType_Enum() : base(new Dictionary<string, string>
    {
        {"", "undefined"},
        {"01", "Proprietary"},
        {"02", "ISBN-10 (International Standard Book Number, pre-2007 (10 digits, or 9 digits plus X, without spaces or hyphens) – now DEPRECATED in ONIX for Books, except where providing historical information for compatibility with legacy systems. It should only be used in relation to products published before 2007 – when ISBN-13 superseded it – and should never be used as the ONLY identifier (it should always be accompanied by the correct GTIN-13 / ISBN-13))"},
        {"03", "GTIN-13"},
        {"04", "UPC"},
        {"05", "ISMN-10 (International Standard Music Number, pre-2008 (M plus nine digits, without spaces or hyphens) – now DEPRECATED in ONIX for Books, except where providing historical information for compatibility with legacy systems. It should only be used in relation to products published before 2008 – when ISMN-13 superseded it – and should never be used as the ONLY identifier (it should always be accompanied by the correct GTIN-12 / ISMN-13))"},
        {"06", "DOI"},
        {"13", "LCCN"},
        {"14", "GTIN-14"},
        {"15", "ISBN-13"},
        {"17", "Legal deposit number"},
        {"22", "URN"},
        {"23", "OCLC number"},
        {"24", "Co-publisher’s ISBN-13"},
        {"25", "ISMN-13"},
        {"26", "ISBN-A"},
        {"27", "JP e-code"},
        {"28", "OLCC number"},
        {"29", "JP Magazine ID"},
        {"30", "UPC12+5"},
        {"31", "BNF Control number"},
        {"34", "ISSN-13"},
        {"35", "ARK"},
    })
    { }
}